# Generated by Django 4.0.3 on 2022-03-21 16:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoper_id', models.CharField(max_length=20, unique=True)),
                ('shopify_id', models.CharField(blank=True, max_length=20, null=True)),
                ('shoper_product_id', models.CharField(blank=True, max_length=20, null=True)),
                ('shopify_product_id', models.CharField(blank=True, max_length=20, null=True)),
                ('shoper_main', models.BooleanField(default=False)),
                ('order', models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth'), (5, 'Fifth'), (6, 'Sixth'), (7, 'Seventh'), (8, 'Eighth'), (9, 'Ninth'), (10, 'Tenth'), (11, 'Eleventh'), (12, 'Twelfth'), (13, 'Thirteenth'), (14, 'Fourteenth'), (15, 'Fifteenth')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)])),
                ('shoper_link', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('shopify_link', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('shoper_unic', models.CharField(max_length=255, unique=True)),
                ('hidden', models.BooleanField(default=False)),
                ('extension', models.CharField(blank=True, max_length=3, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
