# Generated by Django 4.0.5 on 2022-06-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoper_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('shoper_category_is_root', models.IntegerField(blank=True, null=True)),
                ('shoper_order', models.IntegerField(blank=True, null=True)),
                ('shoper_current_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
