# Generated by Django 4.0.4 on 2022-06-02 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(max_length=20)),
                ('shoper_translation_id', models.IntegerField(unique=True)),
                ('related_product_id', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=255)),
                ('short_description', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField()),
                ('is_default', models.BooleanField()),
                ('lang_id', models.IntegerField()),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_description', models.TextField(blank=True)),
                ('seo_keywords', models.TextField(blank=True)),
                ('seo_url', models.CharField(blank=True, max_length=255)),
                ('permalink', models.CharField(max_length=255)),
                ('order', models.IntegerField()),
                ('main_page', models.BooleanField()),
                ('main_page_order', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
