# Generated by Django 4.0.3 on 2022-03-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('vendor', models.CharField(max_length=100)),
                ('shoper_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('shopify_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('ean', models.CharField(max_length=13, unique=True)),
                ('sku', models.CharField(max_length=25, unique=True)),
                ('images', models.ManyToManyField(blank=True, to='images.image')),
            ],
        ),
    ]
