# Generated by Django 4.0.5 on 2022-07-06 20:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoper_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('shoper_type', models.IntegerField(blank=True, null=True)),
                ('shoper_producer_id', models.IntegerField(blank=True, null=True)),
                ('shoper_group_id', models.IntegerField(blank=True, null=True)),
                ('shoper_tax_id', models.IntegerField(blank=True, null=True)),
                ('shoper_main_category_id', models.IntegerField(blank=True, null=True)),
                ('shoper_all_categories_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), size=None)),
                ('shoper_unit_id', models.IntegerField(blank=True, null=True)),
                ('created_shoper', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_shoper', models.CharField(blank=True, max_length=50, null=True)),
                ('shoper_other_price', models.CharField(blank=True, max_length=40, null=True)),
                ('shoper_promo_price', models.CharField(blank=True, max_length=40, null=True)),
                ('shoper_sku', models.CharField(blank=True, max_length=25, unique=True)),
                ('shoper_ean', models.CharField(blank=True, max_length=13)),
                ('shoper_pkwiu', models.CharField(blank=True, max_length=100)),
                ('shoper_is_product_of_day', models.IntegerField(blank=True, null=True)),
                ('shoper_bestseller_tag', models.BooleanField(blank=True, null=True)),
                ('shoper_new_product_tag', models.BooleanField(blank=True, null=True)),
                ('shoper_vol_weight', models.CharField(blank=True, max_length=100)),
                ('shoper_gauge_id', models.IntegerField(blank=True, null=True)),
                ('shoper_currency_id', models.IntegerField(blank=True, null=True)),
                ('shoper_promo_id', models.IntegerField(blank=True, null=True)),
                ('shoper_promo_start', models.CharField(blank=True, max_length=50, null=True)),
                ('shoper_promo_ends', models.CharField(blank=True, max_length=50, null=True)),
                ('shoper_discount_value', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, to='tags.tag')),
            ],
        ),
    ]
